sudo: false
language: node_js
node_js: 10
install: echo "Installation happens in the setup script"
cache:
    directories:
        - node_modules
        - back/node_modules
notifications:
    email: false
script:
    - npm run setup
deploy:
    provider: heroku
    api_key:
        secure: Guo/XxlgMvaNhGUfByDeVOC8vduLm7Cv992s7RQcARWuvWXgm2E687v7cM0v+NxwouRE26JuWdBW4r2CybluFdHcL1RHCm0UHM1ZlwDZc3k9BBZ/94M27ma+DUkrA/5YFGU0+Tp3GQG9QDFMqoUbz75QWstwrHhyRUTSMk38MI0uunogkLRaeJpvSSzB42pGEDcvUkgWPcieUuXp7j06otdk/BNdbpkxdhkoZDqvGwUKrRMF5tkobsj2QNKrFABEEo1tGH+9lm8WLf+L+MPX6z80iZoKS36Rm1378/SmFHLvRQ+sAaqrJ3sBboELCxkBkrDrx99ly8oWW3nRekBoNehEkUHkg3GmF5JnG1+SsOF7OqbmwySBfgceY114LoRKvwrUTIVHCBJnan60bNNuZc3qwY87eu5LKDRk9pZyERcT+VtX4cxNQ/vdkJYmBU9x/C7nnKrOIfTb7VpA00MU+FFfqrWg1e8NtRMVqYs3VJV+xlmWxG7Yr6LHW8JCvQr8W+wgXXysv/NyqHNVqDCb8qEC1pHX+7dGpWyLkOW8rygckKis+uO6YJ9DjokYWNUaZaH3Ca5p8smbrWQnuN5Y+OB02ELdgz1DS+4GrBp908QVJNHrXcR5Ug9SURwScLWj8u4rM4iyAnII6eRm3yjlDcmq1o3hR6aqDfFDuVL6lPU=
    app: dash-gate
true:
    repo: kshitijk83/dash-gate
    branch: master
