export const students: student[] = [
    {
        name: 'Kshitiz Kumar',
        gender: 'M',
        rollno: '17MI513',
        year: '3rd',
        hostel: 'UBH',
        id: Math.random().toString(),
    },
    {
        name: 'Divyanshu Dhawan',
        gender: 'M',
        rollno: '17MI547',
        year: '3rd',
        hostel: 'KBH',
        id: Math.random().toString(),
    },
    {
        name: 'Shubham Thakur',
        gender: 'M',
        rollno: '17MI324',
        year: '3rd',
        hostel: 'UBH',
        id: Math.random().toString(),
    },
    {
        name: 'Shubham Chauhan',
        gender: 'M',
        rollno: '17MI234',
        year: '3rd',
        hostel: 'Himadgri',
        id: Math.random().toString(),
    },
    {
        name: 'Amandeep Pooni',
        gender: 'M',
        rollno: '17MI544',
        year: '3rd',
        hostel: 'Himgiri',
        id: Math.random().toString(),
    },
    {
        name: 'Diksha Rana',
        gender: 'F',
        rollno: '17mi555',
        year: '3rd',
        hostel: 'AGH',
        id: Math.random().toString(),
    },
    {
        name: 'Vineet Sharma',
        gender: 'M',
        rollno: '17MI514',
        year: '3rd',
        hostel: 'DBH',
        id: Math.random().toString(),
    },
    {
        name: 'Tanvi Mahajan',
        gender: 'F',
        rollno: '17mi555',
        year: '3rd',
        hostel: 'AGH',
        id: Math.random().toString(),
    },
    {
        name: 'Shivam Kapila',
        gender: 'M',
        rollno: '17MI517',
        year: '3rd',
        hostel: 'NBH',
        id: Math.random().toString(),
    },
    {
        name: 'Shivam Sood',
        gender: 'M',
        rollno: '17MI519',
        year: '3rd',
        hostel: 'UBH',
        id: Math.random().toString(),
    },
    {
        name: 'Harsh Sharma',
        gender: 'M',
        rollno: '17MI511',
        year: '3rd',
        hostel: 'UBH',
        id: Math.random().toString(),
    },
    {
        name: 'Astha',
        gender: 'F',
        rollno: '17mi555',
        year: '3rd',
        hostel: 'AGH',
        id: Math.random().toString(),
    },
    {
        name: 'Ritika Verma',
        gender: 'F',
        rollno: '17mi555',
        year: '3rd',
        hostel: 'AGH',
        id: Math.random().toString(),
    },
    {
        name: 'Debo',
        gender: 'M',
        rollno: '17MI510',
        year: '3rd',
        hostel: 'Himgiri',
        id: Math.random().toString(),
    },
    {
        name: 'Sahaj Kulshrestha',
        gender: 'M',
        rollno: '17MI510',
        year: '3rd',
        hostel: 'Himgiri',
        id: Math.random().toString(),
    },
    {
        name: 'Ankit Sharma',
        gender: 'M',
        rollno: '17MI413',
        year: '3rd',
        hostel: 'DBH',
        id: Math.random().toString(),
    },
    {
        name: 'Vinay Sharma',
        gender: 'M',
        rollno: '17MI613',
        year: '3rd',
        hostel: 'DBH',
        id: Math.random().toString(),
    },
    {
        name: 'Mayank Sharma',
        gender: 'M',
        rollno: '17MI113',
        year: '3rd',
        hostel: 'NBH',
        id: Math.random().toString(),
    },
];
