// *===========HTTP ACTION TYPES==============
// eslint-disable-next-line
export const HTTP_ACTION_TYPES = {
    SENDING: 'SENDING',
    RESPONSE: 'RESPONSE',
    ERROR: 'ERROR',
    CLEAR: 'CLEAR',
};

// *=========== ADD REMOVE HANDLER============
export const TODO_ACTION_TYPES = {
    ADD: 'ADD',
    UPDATE: 'UPDATE',
    REMOVE: 'REMOVE',
    SET: 'SET',
};

// *=========== NETWORK CONFIG================
export const NETWORK_CONFIG_ACTION_TYPES = {
    SET_CONFIG_OBJ: 'SET_CONFIG_OBJ',
    SET_NETWORK_CONFIG: 'SET_NETWORK_CONFIG',
    SET_ORGANIZATION_NUM: 'SET_ORGANIZATION_NUM',
    SET_PEER: 'SET_PEER',
    SET_PEERS_NUM: 'SET_PEERS_NUM',
    SET_ORGANIZATION_NAME: 'SET_ORGANIZATION_NAME',
    SET_PEER_TYPE: 'SET_PEER_TYPE',
    SET_PEER_DEPLOY_VM: 'SET_PEER_DEPLOY_VM',
    SET_ANCHOR: 'SET_ANCHOR',
    SET_CA: 'SET_CA',
    SET_ROOT_PEER: 'SET_ROOT_PEER',
    SET_CA_ORG: 'SET_CA_ORG',
    SET_CA_HOST: 'SET_CA_HOST',
};

// *=========== ORDERER CONFIG================
export const ORDERER_CONFIG_ACTION_TYPES = {
    SET_ORDERERS_ARR: 'SET_ORDERERS_ARR',
    SET_BATCH_TIMEOUT: 'SET_BATCH_TIMEOUT',
    SET_MAX_MESSAGE_COUNT: 'SET_MAX_MESSAGE_COUNT',
    SET_ABSOLUTE_MAX_BYTES: 'SET_ABSOLUTE_MAX_BYTES',
    SET_PREFERRED_MAX_BYTES: 'SET_PREFERRED_MAX_BYTES',
    SET_ORDERER_TYPE: 'SET_ORDERER_TYPE',
    SET_ORDERER_COUNT: 'SET_ORDERER_COUNT',
    SET_ORDERERS: 'SET_ORDERERS',
    SET_ROOT_ORDERER: 'SET_ROOT_ORDERER',
    SET_DEPLOY_HOST: 'SET_DEPLOY_HOST',
};

// *=========== CHANNEL CONFIG================
export const CHANNEL_CONFIG_ACTION_TYPES = {
    SET_CHANNELS: 'SET_CHANNELS',
    SET_CHANNEL_CONFIG: 'SET_CHANNEL_CONFIG',
    DELETE_CHANNEL_CONFIG: 'DELETE_CHANNEL_CONFIG',
    EDIT_CHANNEL: 'EDIT_CHANNEL',
};

// *=========== CHAINCODE CONFIG================
export const CHAINCODE_CONFIG_ACTION_TYPES = {
    SET_CHAINCODES: 'SET_CHAINCODES',
    ADD_CHAINCODE: 'ADD_CHANNEL_CONFIG',
    DELETE_CHAINCODE: 'DELETE_CHAINCODE',
    EDIT_CHAINCODE: 'EDIT_CHAINCODE',
};

// *=========== APP FLOW =======================
export const APP_FLOW_ACTION_TYPES = {
    SET_OPEN: 'SET_OPEN',
    SET_ALL_OPEN: 'SET_ALL_OPEN',
};
